### ISSUE TITLE
`tibble::tribble()` support?

### ISSUE THREAD

**Issue by andrewheiss** [atsyplenkov/pastum#11]
Thanks for making this extension! I've missed {datapasta} in Positron (and would often open RStudio just to use it there 😁)

{datapasta} has an option to format the clipboard for `tibble::tribble()` (rowwise tibble) in addition to `tibble::tibble()`:

```
tibble::tribble(
  ~some_column, ~min, ~max, ~`Some other column`,
  "thing 1", 5, 3, "testing 1", 
  "thing 2", 6, 8, "testing 2", 
  "thing 3", 62, 532, "testing 3"
)
```

It's often really helpful to be able to define tables rowwise like this. It would be neat if `pastum` could support this too, perhaps as one of the options in the list of frameworks, like "tibble::tribble() ✨" or something similar:

<img width="327" alt="image" src="https://github.com/user-attachments/assets/ca3af5f0-a367-4ff4-a556-74c0484eade9">

**Comment by atsyplenkov** [comment]
Thanks for flagging this! I will definitely add it to the next release

**Comment by atsyplenkov** [comment]
Hey @andrewheiss, it seems like it was an easy fix. See the `v0.1.0` version on the marketplace and releases page. Please let me know what you think.

It works for me:

```
Nationality 	Population (2018)
England 	2,748
India 	1,539
China 	1,440
Australia 	1,155
South Africa 	903
Philippines 	693
Fiji 	528
United States 	468
Samoa 	441
Malaysia 	390 
```

```r
tibble::tribble(
  ~Nationality,    ~Population2018,
  "England",       2748L,          
  "India",         1539L,          
  "China",         1440L,          
  "Australia",     1155L,          
  "South Africa",  903L,           
  "Philippines",   693L,           
  "Fiji",          528L,           
  "United States", 468L,           
  "Samoa",         441L,           
  "Malaysia",      390L
)
```
